# This recovers all of the information needed for the comparison of DE genes to random genes. (a) gene lists, (b) TPMs, (c) fold change of TPMs
# TAS

library(qvalue)

# Call the differential expression gene lists.####
pval_mouse_12 <- read.delim("raw_data/edgeR_outputs/mouse_all_ONgene_pvals/mouse_edgeR_lrt.1vs2_all_ONgene.txt")
pval_mouse_23 <- read.delim("raw_data/edgeR_outputs/mouse_all_ONgene_pvals/mouse_edgeR_lrt.2vs3_all_ONgene.txt")
pval_mouse_34 <- read.delim("raw_data/edgeR_outputs/mouse_all_ONgene_pvals/mouse_edgeR_lrt.3vs4_all_ONgene.txt")
pval_mouse_45 <- read.delim("raw_data/edgeR_outputs/mouse_all_ONgene_pvals/mouse_edgeR_lrt.4vs5_all_ONgene.txt")

pval_alligator_12 <- read.delim("raw_data/edgeR_outputs/alligator_all_ONgene_pvals/alligator_edgeR_lrt.1vs2_all_ONgene.txt")
pval_alligator_23 <- read.delim("raw_data/edgeR_outputs/alligator_all_ONgene_pvals/alligator_edgeR_lrt.2vs3_all_ONgene.txt")
pval_alligator_34 <- read.delim("raw_data/edgeR_outputs/alligator_all_ONgene_pvals/alligator_edgeR_lrt.3vs4_all_ONgene.txt")
pval_alligator_45 <- read.delim("raw_data/edgeR_outputs/alligator_all_ONgene_pvals/alligator_edgeR_lrt.4vs5_all_ONgene.txt")

pval_chicken_12 <- read.delim("raw_data/edgeR_outputs/chicken_pairwise_all_ONgene_pvals/chicken_edgeR_lrt.stage.1vs2_all_ONgene.txt")
pval_chicken_23 <- read.delim("raw_data/edgeR_outputs/chicken_pairwise_all_ONgene_pvals/chicken_edgeR_lrt.stage.2vs3_all_ONgene.txt")
pval_chicken_34 <- read.delim("raw_data/edgeR_outputs/chicken_pairwise_all_ONgene_pvals/chicken_edgeR_lrt.stage.3vs4_all_ONgene.txt")

# Calculate q values
qval_mouse_12 <- pval_mouse_12[(pval_mouse_12$FDR < 0.05),]
qval_mouse_23 <- pval_mouse_23[(pval_mouse_23$FDR < 0.05),]
qval_mouse_34 <- pval_mouse_34[(pval_mouse_34$FDR < 0.05),]
qval_mouse_45 <- pval_mouse_45[(pval_mouse_45$FDR < 0.05),]

qval_alligator_12 <- pval_alligator_12[(pval_alligator_12$FDR < 0.05),]
qval_alligator_23 <- pval_alligator_23[(pval_alligator_23$FDR < 0.05),]
qval_alligator_34 <- pval_alligator_34[(pval_alligator_34$FDR < 0.05),]
qval_alligator_45 <- pval_alligator_45[(pval_alligator_45$FDR < 0.05),]

qval_chicken_12 <- pval_chicken_12[p.adjust(pval_chicken_12$PValue, method = "BH") < 0.05,] # still needs to be calculatd for these files
qval_chicken_23 <- pval_chicken_23[p.adjust(pval_chicken_23$PValue, method = "BH") < 0.05,]
qval_chicken_34 <- pval_chicken_34[p.adjust(pval_chicken_34$PValue, method = "BH") < 0.05,]

# Reduce to the othologous TFs for direct comparisons.
one2one_list <- read.delim("output_files/amggmm_TFs_1049.txt") # this is generated by the script "mklist_one_to_one_TFS_ammmgg.R"

one_to_one_gg_12 <- one2one_list[one2one_list$gg_gene_id %in% rownames(qval_chicken_12),]
one_to_one_gg_23 <- one2one_list[one2one_list$gg_gene_id %in% rownames(qval_chicken_23),]
one_to_one_gg_34 <- one2one_list[one2one_list$gg_gene_id %in% rownames(qval_chicken_34),]

one_to_one_mm_12 <- one2one_list[one2one_list$mm_gene_id %in% rownames(qval_mouse_12),]
one_to_one_mm_23 <- one2one_list[one2one_list$mm_gene_id %in% rownames(qval_mouse_23),]
one_to_one_mm_34 <- one2one_list[one2one_list$mm_gene_id %in% rownames(qval_mouse_34),]
one_to_one_mm_45 <- one2one_list[one2one_list$mm_gene_id %in% rownames(qval_mouse_45),]

one_to_one_am_12 <- one2one_list[one2one_list$am_gene_id %in% rownames(qval_alligator_12),]
one_to_one_am_23 <- one2one_list[one2one_list$am_gene_id %in% rownames(qval_alligator_23),]
one_to_one_am_34 <- one2one_list[one2one_list$am_gene_id %in% rownames(qval_alligator_34),]
one_to_one_am_45 <- one2one_list[one2one_list$am_gene_id %in% rownames(qval_alligator_45),]


# Calculate TPMs ####
# mouse data ####
HTSeq_mm <- read.table("raw_data/mm_HTSeq.txt", sep="\t", header=T)
gene_length_mm <- read.delim ("raw_data/mm_gene_length_median.txt")
merged_mm <- merge(gene_length_mm, HTSeq_mm, by="mm_gene_id")
merged_mm <- merge(merged_mm, one2one_list, by="mm_gene_id")

# alligator data ####
HTSeq_am <- read.delim("raw_data/am_HTSeq.txt")
gene_length_am <- read.delim("raw_data/am_gene_length_median.txt")
am_gene_id <- read.delim("raw_data/am_gene_annotations.txt", na.strings = "")
am_gene_id <- am_gene_id[c("am_gene_id", "gene_symbol")]
merged_am <-merge(am_gene_id, HTSeq_am, by="am_gene_id")
merged_am <-merge(gene_length_am, merged_am, by="am_gene_id")
merged_am <-merge(one2one_list, merged_am, by="gene_symbol") 

# chicken data ####
HTSeq_gg <- read.delim ("raw_data/gg_HTseq.txt")
gg_gene_id <- read.delim ("raw_data/gal_names_length_median.txt", na.strings = "", col.names = c("gg_gene_id", "length_gg", "gene_symbol"))
merged_gg <-merge(gg_gene_id, HTSeq_gg, by="gg_gene_id")
merged_gg <-merge(merged_gg, one2one_list, by="gg_gene_id")

# calc TPM
fn.TPM_mm <-function(sample) {
  (sample*75*10^6)/(merged_mm$length_mm*sum((sample*75)/merged_mm$length_mm))
}
TPM_mm <- as.data.frame(sapply(merged_mm[3:(length(merged_mm)-3)], fn.TPM_mm))

fn.TPM_am <-function(sample) {
  (sample*75*10^6)/(merged_am$length_am*sum((sample*75)/merged_am$length_am))
}
TPM_am <- as.data.frame(sapply(merged_am[7:length(merged_am)], fn.TPM_am))

fn.TPM_gg <-function(sample) {
  (sample*34*10^6)/(merged_gg$length_gg*sum((sample*34)/merged_gg$length_gg))
}
TPM_gg <- as.data.frame(sapply(merged_gg[4:(length(merged_gg)-3)], fn.TPM_gg))

# tidy R
remove(am_gene_id, gene_length_am, gene_length_mm, gg_gene_id, one2one_list,
       pval_alligator_12, pval_alligator_23, pval_alligator_34, pval_alligator_45,
       pval_chicken_12, pval_chicken_23, pval_chicken_34, 
       pval_mouse_12, pval_mouse_23, pval_mouse_34, pval_mouse_45,
       qval_alligator_12, qval_alligator_23, qval_alligator_34, qval_alligator_45,
       qval_chicken_12, qval_chicken_23, qval_chicken_34, 
       qval_mouse_12, qval_mouse_23, qval_mouse_34, qval_mouse_45,
       fn.TPM_am, fn.TPM_gg, fn.TPM_mm,
       HTSeq_am, HTSeq_gg, HTSeq_mm)

# run 1-103 of original.

is.nan.data.frame <- function(x) # set function to replace NaNs in tables.
  do.call(cbind, lapply(x, is.nan))
names(merged_am)[names(merged_am) == 'am_gene_id.x'] <- 'am_gene_id'

# Calculate fold change for all genes, all species ####
# chicken #### 
gene_symbol <- merged_gg$gene_symbol.x
gg_gene_id <- merged_gg$gg_gene_id

# chicken hindlimb D1/D2
tpm_fold_change_gg <- data.frame (gene_symbol, gg_gene_id,
                                  "change1v2_e"= (TPM_gg$gg_HL_D2_E-TPM_gg$gg_HL_D1_E) / ((TPM_gg$gg_HL_D2_E+TPM_gg$gg_HL_D1_E)/2),
                                  "change1v2_l"= (TPM_gg$gg_HL_D2_L-TPM_gg$gg_HL_D1_L) / ((TPM_gg$gg_HL_D2_L+TPM_gg$gg_HL_D1_L)/2),
                                  "change2v3_e"= (TPM_gg$gg_HL_D3_E-TPM_gg$gg_HL_D2_E) / ((TPM_gg$gg_HL_D3_E+TPM_gg$gg_HL_D2_E)/2),
                                  "change2v3_l"= (TPM_gg$gg_HL_D3_L-TPM_gg$gg_HL_D2_L) / ((TPM_gg$gg_HL_D3_L+TPM_gg$gg_HL_D2_L)/2),
                                  "change3v4_e"= (TPM_gg$gg_HL_D4_E-TPM_gg$gg_HL_D3_E) / ((TPM_gg$gg_HL_D4_E+TPM_gg$gg_HL_D3_E)/2),
                                  "change3v4_l"= (TPM_gg$gg_HL_D4_L-TPM_gg$gg_HL_D3_L) / ((TPM_gg$gg_HL_D4_L+TPM_gg$gg_HL_D3_L)/2))
tpm_fold_change_gg[is.nan.data.frame(tpm_fold_change_gg)] <- 0

#  mouse ####
TPM_mm_1 <- rowMeans(TPM_mm[1:3])
TPM_mm_2 <- rowMeans(TPM_mm[4:6])
TPM_mm_3 <- rowMeans(TPM_mm[7:9])
TPM_mm_4 <- rowMeans(TPM_mm[10:12])
TPM_mm_5 <- rowMeans(TPM_mm[13:15])
TPM_mm_avg <- data.frame("mm_gene_id"=as.vector(merged_mm$mm_gene_id),
                         "TPM_mm_1"=rowMeans(TPM_mm[1:3]),
                         "TPM_mm_2"=rowMeans(TPM_mm[4:6]),
                         "TPM_mm_3"=rowMeans(TPM_mm[7:9]),
                         "TPM_mm_4"=rowMeans(TPM_mm[10:12]),
                         "TPM_mm_5"=rowMeans(TPM_mm[13:15]))

gene_symbol <- merged_mm$gene_symbol
mm_gene_id <- merged_mm$mm_gene_id

tpm_fold_change_mm <- data.frame (gene_symbol, mm_gene_id,
                                  "change1v2"=(TPM_mm_2-TPM_mm_1) / ((TPM_mm_2+TPM_mm_1)/2),
                                  "change2v3"=(TPM_mm_3-TPM_mm_2) / ((TPM_mm_3+TPM_mm_2)/2),
                                  "change3v4"=(TPM_mm_4-TPM_mm_3) / ((TPM_mm_4+TPM_mm_3)/2),
                                  "change4v5"=(TPM_mm_5-TPM_mm_4) / ((TPM_mm_5+TPM_mm_4)/2) )
tpm_fold_change_mm[is.nan.data.frame(tpm_fold_change_mm)] <- 0


# alligator ####
TPM_am_1_e <- rowMeans(TPM_am[1:3])
TPM_am_2_e <- rowMeans(TPM_am[4:6])
TPM_am_3_e <- rowMeans(TPM_am[7:8])
TPM_am_4_e <- rowMeans(TPM_am[9:11])
TPM_am_5_e <- rowMeans(TPM_am[12:14])

TPM_am_1_l <- rowMeans(TPM_am[15:17])
TPM_am_2_l <- rowMeans(TPM_am[18:20])
TPM_am_3_l <- rowMeans(TPM_am[21:23])
TPM_am_4_l <- rowMeans(TPM_am[24:26])
TPM_am_5_l <- rowMeans(TPM_am[27:29])

TPM_am_avg <- data.frame("am_gene_id"=as.vector(merged_am$am_gene_id),
                         "TPM_am_1_e"=rowMeans(TPM_am[1:3]), "TPM_am_2_e"=rowMeans(TPM_am[4:6]), "TPM_am_3_e"=rowMeans(TPM_am[7:8]), "TPM_am_4_e"=rowMeans(TPM_am[9:11]), "TPM_am_5_e"=rowMeans(TPM_am[12:14]),
                         "TPM_am_1_l"=rowMeans(TPM_am[15:17]), "TPM_am_2_l"=rowMeans(TPM_am[18:20]), "TPM_am_3_l"=rowMeans(TPM_am[21:23]), "TPM_am_4_l"=rowMeans(TPM_am[24:26]), "TPM_am_5_l"=rowMeans(TPM_am[27:29]))

tpm_fold_change_am <- data.frame ("gene_symbol"=merged_am$gene_symbol,
                                  "am_gene_id"=merged_am$am_gene_id,
                                  "change1v2_e"=(TPM_am_2_e-TPM_am_1_e) / ((TPM_am_2_e+TPM_am_1_e)/2),
                                  "change1v2_l"=(TPM_am_2_l-TPM_am_1_l) / ((TPM_am_2_l+TPM_am_1_l)/2),
                                  "change2v3_e"=(TPM_am_3_e-TPM_am_2_e) / ((TPM_am_3_e+TPM_am_2_e)/2),
                                  "change2v3_l"=(TPM_am_3_l-TPM_am_2_l) / ((TPM_am_3_l+TPM_am_2_l)/2),
                                  "change3v4_e"=(TPM_am_4_e-TPM_am_3_e) / ((TPM_am_4_e+TPM_am_3_e)/2),
                                  "change3v4_l"=(TPM_am_4_l-TPM_am_3_l) / ((TPM_am_4_l+TPM_am_3_l)/2),
                                  "change4v5_e"=(TPM_am_5_e-TPM_am_4_e) / ((TPM_am_5_e+TPM_am_4_e)/2),
                                  "change4v5_l"=(TPM_am_5_l-TPM_am_4_l) / ((TPM_am_5_l+TPM_am_4_l)/2) )
tpm_fold_change_am[is.nan.data.frame(tpm_fold_change_am)] <- 0